### ISSUE TITLE
Databases should not be exposed to the Docker host

### ISSUE THREAD

**Issue by griffinht** [CivMC/CivDocker#17]
Why are all the databases exposed to the Docker host with the `ports` mapping? This is not necessary for inter container communication. Unless there is some kind of external program that needs access to the databases, they should not be exposed to the host (where they could possibly be exposed to the internet!).

Additionally, these services don't seem to need internet access. Why not disable that as well ([example](https://stackoverflow.com/questions/39913757/restrict-internet-access-docker-container))? I could create a PR to show what I am suggesting.

**Comment by AngrySoundTech** [comment]
They're exposed so that we can connect db clients to them (like pgadmin or datagrip).

The docker-compose file here isn't meant to run a production stack, it's meant to stand up a local test server so you can make sure your changes work
