### ISSUE TITLE
Add new city spawns

### ISSUE THREAD

**Issue by AngrySoundTech** [CivMC/CivDocker#213]
Running list of any triaged from tickets

| Name | Location | Contact |
| - | - | - |
| Winterbourne | -37, -7585 | 795046514363727923 |

**Comment by WilliamLarsen** [comment]
PR here:
https://github.com/CivMC/CivDocker/pull/231/files

Let me know if anything is wrong as this is my first PR for this repo

**Comment by RedDevel2** [comment]
Guess this can remain open?
