### ISSUE TITLE
Add mapart protections/copyright features

### ISSUE THREAD

**Issue by RedDevel2** [CivMC/CivDocker#214]
make the cartography table give a lore + Persistent data container when copying a map
make sure that it preserves them when locking
disable further copying if it has that tag

Disable copying of maps in normal crafting menu by use of craftenhance

**Comment by MrJeremyFisher** [comment]
Would a command based locking system be acceptable? It would be akin to brewery's unlabel command, and avoid the hassle of dealing with preserving a still copyable original in the cartography table.

**Comment by RedDevel2** [comment]
It would, 
As long as it's unable to be copied by the cartography table when it's locked.

**Comment by RedDevel2** [comment]
https://github.com/CivMC/SimpleAdminHacks/pull/80

**Comment by RedDevel2** [comment]
Closed with https://github.com/CivMC/Civ/pull/237
