### ISSUE TITLE
Reevaluate Mobs spawn/despawn range

### ISSUE THREAD

**Issue by RedDevel2** [CivMC/CivDocker#234]
There's been complains that the spawn area is too small for farms to work properly

**Comment by Rinvincibl3** [comment]
Good Morning, 

While I absolutely understand the needs of a server like CivMC to have non-vanilla spawn rules, to avoid mob-generation abuse, and to ensure an even distribution of mob spawning, the spawn rates and radii are quite low/small respectively. 

On one level, I'd like to see the spawn rates raised. It feels strange that even for time-intensive, well-built, and carefully planned mob farms, the rates are still low enough to make a project feel wasted, and the infrequency of mob spawning can make the project difficult to debug on live servers (sometimes needing to wait minutes or hours for mobs to spawn across the tested area)

More generally, as well, I believe returning to vanilla spawn radii would make sense. Of course, the rates, limits, and mechanics a should remain different from Vanilla to ensure server health, but the distances themselves seem like they have no need of being different from the vanilla ranges for spawn, motion, and despawn. Especially with the currently low spawn rates, I would be surprised if moving to vanilla radii negatively affected server performance. 

Thanks for all you do!
