### ISSUE TITLE
Orebfuscator has high server usage

### ISSUE THREAD

**Issue by wingzero54** [CivMC/CivDocker#37]
Regularly 2-6% of the server is dedicated to Orebfuscator, specifically Deobfuscation listener and Proximity listener. What are our options here for reducing the impact? 

![image](https://user-images.githubusercontent.com/7980903/176530229-0b31aaee-1749-4e11-9d73-17142cb3d693.png)

**Comment by wingzero54** [comment]
We're hopeful that removing excess blocks from proximity hider will make an impact on the high usage
https://github.com/CivMC/CivDocker/commit/ba6d853b1ea6934ee4807ea02979be070644a272

**Comment by ProgrammerDan** [comment]
This isn't a terribly high usage for a plugin as critical to anti-xray as orebfuscator, I'd think. 

I don't have any Devoted tick measures saved, but a few percent strikes me as normal. It's a fairly heavy plugin, in general.

**Comment by wingzero54** [comment]
2% is definitely acceptable, but lately it has regularly been around 6-8% which is too high

**Comment by ProgrammerDan** [comment]
Fair enough. 

In the 6-8% situations, do you find the distributions similar to above, where the BlockDamageEvent is the largest issue? Or, as your change would indicate, is ProximityListener jumping to the top of the list?
