### ISSUE TITLE
Increase reinforcement maturation times

### ISSUE THREAD

**Issue by awoo-civ** [CivMC/CivDocker#70]
Current reinforcement maturation times:
 - Stone: 5min
 - Iron: 30min
 - Diamond: 4h

These are short enough to be irrelevant. Nobody takes them into account when doing anything.

In my opinion infrastructure built ad-hoc should not be as good as already-existing infrastructure as well as that players should have the opportunity to break structures encroaching on their land within a reasonable time period. Current maturation times are so low that there's no realistic scenario in which someone would try to break unmatured blocks to take advantage of their weakened state. There's simply not enough time to act.

To start with I propose going with a maturation time of one day for diamond, to match bastion maturation time:
 - Stone: 30min
 - Iron: 3h 30min
 - Diamond: 1d

Note that I think these are too low still, but it'd at least be a step in the right direction.

**Comment by wingzero54** [comment]
This is a solid point and good recommendation, I'm just wondering if anyone else has any input?

**Comment by Maxopoly** [comment]
For reference, note that the damage done to maturing reinforcements is multiplied by the inverse of the maturation progress. Meaning a maturation which has completed  `1/x` of its maturation time has its damage taken multiplied by x.

**Comment by AngrySoundTech** [comment]
Resolved by #87
